spring.application.name=propdeals
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.taypkqqcgjqnyserkwgy
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
